### ISSUE TITLE
Skjermleseren fungerer ikke med lulesamisk

### ISSUE THREAD

**Issue by ilm024** [giellalt/speech-smj#2]
Når jeg vil bruke skjermleseren for den lulesamiske stemmen Nihkol, fungerer den ikke slik som den skal. Den leser bare teksten etter siste komma, selv om jeg "ber" om å få lest hele siden, eller hele avsnittet. 

Jeg bruker en PC med Windows 11. 

Jeg har filmet det hele problemet, hvor jeg gjør nøyaktig det samme for svensk stemme:

https://github.com/user-attachments/assets/42d6427b-a826-4caf-a466-90e3ebfac345

https://github.com/user-attachments/assets/4d4dfbcc-c16a-4fc6-91c6-052c6fa7ccf9

**Comment by ilm024** [comment]
Det er samme problem med alle stemmene. Og en ting til: selv om jeg velger "Ábmut" så er det Nihkols stemme som høres.

**Comment by snomos** [comment]
Duplicate of https://github.com/divvun/TTS-bugs/issues/3.
